### ISSUE TITLE
PopupException: Popup can have only one widget as content

### ISSUE THREAD

**Issue by yunmanger1** [Zogg/FishLife#3]
Kivy==1.7.2
OS: Linux mint olivia

    Traceback (most recent call last):
       File "main.py", line 274, in <module>
         FishLifeBones().run()
       File "/usr/lib/python2.7/dist-packages/kivy/app.py", line 600, in run
         runTouchApp()
       File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 454, in runTouchApp
         EventLoop.window.mainloop()
       File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_pygame.py", line 325, in mainloop
         self._mainloop()
       File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_pygame.py", line 231, in _mainloop
         EventLoop.idle()
       File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 294, in idle
         Clock.tick()
       File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 370, in tick
         self._process_events()
       File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 481, in _process_events
         if event.tick(self._last_tick) is False:
       File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 280, in tick
         ret = callback(self._dt)
       File "/usr/lib/python2.7/dist-packages/kivy/animation.py", line 304, in _update
         self.stop(widget)
       File "/usr/lib/python2.7/dist-packages/kivy/animation.py", line 188, in stop
         self.dispatch('on_complete', widget)
       File "_event.pyx", line 281, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4136)
       File "main.py", line 213, in begin_game
         self.root = self.fishlife = FishLifeGame()
       File "main.py", line 93, in __init__
         self.victory_screen = FishLifeScore()
       File "main.py", line 74, in __init__
         super(FishLifeScore, self).__init__()
       File "/usr/lib/python2.7/dist-packages/kivy/uix/modalview.py", line 149, in __init__
         super(ModalView, self).__init__(**kwargs)
       File "/usr/lib/python2.7/dist-packages/kivy/uix/anchorlayout.py", line 62, in __init__
         super(AnchorLayout, self).__init__(**kwargs)
       File "/usr/lib/python2.7/dist-packages/kivy/uix/layout.py", line 61, in __init__
         super(Layout, self).__init__(**kwargs)
       File "/usr/lib/python2.7/dist-packages/kivy/uix/widget.py", line 163, in __init__
         Builder.apply(self)
       File "/usr/lib/python2.7/dist-packages/kivy/lang.py", line 1429, in apply
         self._apply_rule(widget, rule, rule)
       File "/usr/lib/python2.7/dist-packages/kivy/lang.py", line 1532, in _apply_rule
         widget.add_widget(child)
       File "/usr/lib/python2.7/dist-packages/kivy/uix/popup.py", line 149, in add_widget
         'Popup can have only one widget as content')
     kivy.uix.popup.PopupException: Popup can have only one widget as content

**Comment by russellballestrini** [comment]
Issue still persists and I'm on Fedora 21 Linux with Kivy 1.8.0

**Comment by Zogg** [comment]
Hi,

you have to use the old Kivy version - 1.0.9, which was active during time this contest was run. https://github.com/Zogg/FishLife/issues/2

**Comment by russellballestrini** [comment]
Hey @zogg any reason you don't want to pull in that commit I referenced?  Even though the contest is over, your game is a VERY good Kivy example.

**Comment by Zogg** [comment]
Hi @russellballestrini , I dont know... I'v only noticed the reference after I made a comment 9 days ago. I didnt notice the attention that FishLife has received during the years. It is really great to hear, that the game and the code is useful and an example to many.

WIth what kivy version does the pull request work?

**Comment by russellballestrini** [comment]
The latest on Ubuntu 14.04 and fedora 21 which is 1.8.x

Although, I wouldn't be superseded if it game would work with 1.9.0
released this month.

I can perform test and or verification one it's merged in.

**Comment by Zogg** [comment]
Merged in. If you could test and verify that would be a great great great bonus.

**Comment by Zogg** [comment]
Tested and works. Thank you, @russellballestrini, for encouragement, your words really motivated me to look into the project from a new point of view.

**Comment by russellballestrini** [comment]
Thanks! Sorry I've been swamped over here!  Happy it worked, knew it would.
