### ISSUE TITLE
Not working with only touchpad

### ISSUE THREAD

**Issue by oxidworks** [Zogg/FishLife#6]
Tried this demo on my laptop. Ubuntu 14.04, Kivy 1.9. Cant get it working.

Maybe because of this:

```
[INFO   ] [Base        ] Start application main loop
 Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
     self.run()
   File "/usr/lib/python2.7/threading.py", line 754, in run
     self.__target(*self.__args, **self.__kwargs)
   File "/usr/lib/python2.7/dist-packages/kivy/input/providers/mtdev.py", line 197, in _thread_run
     _device = Device(_fn)
   File "/usr/lib/python2.7/dist-packages/kivy/lib/mtdev.py", line 131, in __init__
     self._fd = os.open(filename, os.O_NONBLOCK | os.O_RDONLY)
 OSError: [Errno 13] Permission denied: '/dev/input/event6'
```

**Comment by oxidworks** [comment]
Working after updating to Kivy Version 1.9.1
